export const colorList = [
  "#FFD700", // Yellow
  "#FFA500", // Orange
  "#FF1493", // Pink
  "#00FF00", // Green
  "#DDA0DD", // Purple
  "#00FFFF", // Cyan
  "#AFEEEE", // Light Blue
  "#FF4500", // Red-Orange
  "#800080", // Purple
  "#32CD32", // Lime Green
  "#1E90FF", // Dodger Blue
  "#FF69B4", // Hot Pink
  "#4682B4", // Steel Blue
];

export const colorListHome = [
  "#FFD700", // Yellow
  "#FF1493", // Pink
  "#00FF00", // Green
  "#00FFFF", // Cyan
];

export interface Icon {
  img: string;
  style: string;
}

export const icons: Icon[] = [
  { img: "metallic.jpg", style: "Metallic" },
  { img: "polygon.jpg", style: "Polygon" },
  { img: "pixelated.jpg", style: "Pixelated" },
  { img: "clay.jpg", style: "Clay" },
  { img: "neon.jpg", style: "Neon" },
  { img: "cartoonish.jpg", style: "Cartoonish" },
  { img: "3d.jpg", style: "3d" },
  { img: "doodle.jpg", style: "Doodle" },
  { img: "minimalistic.jpg", style: "Minimalistic" },
  { img: "sticker.jpg", style: "Sticker" },
  { img: "realistic.jpg", style: "Realistic" },
  { img: "origami.jpg", style: "Origami" },
  { img: "chalckboard.jpg", style: "Chalkboard" },
  { img: "woodcut.jpg", style: "Woodcut" },
];

export const iconsHome: Icon[] = [
  { img: "doodle.jpg", style: "Doodle" },
  { img: "minimalistic.jpg", style: "Minimalistic" },
  { img: "sticker.jpg", style: "Sticker" },
  { img: "metallic.jpg", style: "Metallic" },
  { img: "pixelated.jpg", style: "Pixelated" },
];

export const iconsCarousel: string[] = [
  "1.jpg",
  "2.jpg",
  "3.jpg",
  "metallic.jpg",
  "polygon.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
  "1.jpg",
  "2.jpg",
  "3.jpg",
  "metallic.jpg",
  "polygon.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
  "1.jpg",
  "2.jpg",
  "3.jpg",
  "metallic.jpg",
  "polygon.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
  "1.jpg",
  "2.jpg",
  "3.jpg",
  "metallic.jpg",
  "polygon.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
  "w.jpg",
  "pixelated.jpg",
  "maple-leaf.png",
  "clay.jpg",
  "neon.jpg",
  "yummy-burger.jpg",
  "turtle.jpg",
  "BroccoloSwag.jpg",
  "rabbit.jpg",
  "cartoonish.jpg",
  "3d.jpg",
  "doodle.jpg",
  "hamburger.jpg",
  "minimalistic.jpg",
  "sticker.jpg",
  "realistic.jpg",
  "origami.jpg",
  "chalckboard.jpg",
  "woodcut.jpg",
  "shoes.jpg",
];
export const imagesOptions = [1, 2, 3, 4, 5];

export const plans: Plan[] = [
  {
    price: 5,
    credits: 50,
    name: "50 credits",
    description: "0.10$ per image",
    id: "pr_50",
  },
  {
    price: 9,
    credits: 100,
    name: "100 credits",
    description: "0.09$ per image",
    id: "pr_100",
  },
  {
    price: 20,
    credits: 250,
    name: "250 credits",
    description: "0.08$ per image",
    id: "pr_250",
  },
];

export const footerLinks = [
  { href: "", text: "Terms & Conditions" },
  { href: "", text: "Privacy Policy" },
  { href: "", text: "Refound Policy" },
];
