import Navbar from "@/components/Navbar";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import type { Metadata } from "next";
import Providers from "../containers/providers";
import { Toaster } from "@/components/ui/toaster";
import Modal from "@/components/modal-credits";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={cn(
            "bg-gradient-to-br from-blue-900 via-indigo-900 to-violet-900 h-screen w-screen flex flex-col items-center overflow-hidden",
            inter.className
          )}
        >
          <Analytics />
          <Toaster />
          <Navbar />
          <Modal />
          <main className="h-full w-full overflow-scroll">
            <NextTopLoader
              color="#2299DD"
              initialPosition={0.08}
              crawlSpeed={200}
              height={3}
              crawl={true}
              easing="ease"
              speed={200}
              shadow="0 0 10px #2299DD,0 0 5px #2299DD"
            />
            {children}
          </main>
        </body>
      </html>
    </Providers>
  );
}
